require "test_helper"
require "open3"
require "tempfile"

class DatabaseRepresentationTest < ActiveSupport::TestCase
  EXPECTED_POSTGRESQL_MAJOR = 18
  EXPECTED_VECTOR_VERSION = "0.8.5"

  test "uses the SQL schema representation and PostgreSQL timestamptz" do
    assert_equal :sql, Rails.application.config.active_record.schema_format
    assert_equal :timestamptz, ActiveRecord::ConnectionAdapters::PostgreSQLAdapter.datetime_type

    structure = Rails.root.join("db/structure.sql")
    assert_predicate structure, :exist?
    assert_includes(
      structure.read,
      "CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public VERSION '0.8.5';"
    )
  end

  test "runs on the approved PostgreSQL and pgvector versions" do
    server_version_num = connection.select_value("SHOW server_version_num").to_i
    vector_version = connection.select_value(<<~SQL.squish)
      SELECT extversion
      FROM pg_extension
      WHERE extname = 'vector'
    SQL

    assert_equal EXPECTED_POSTGRESQL_MAJOR, server_version_num / 10_000
    assert_equal EXPECTED_VECTOR_VERSION, vector_version
    assert Nudge::DatabaseCompatibility.verify!(connection)
  end

  test "rejects incompatible PostgreSQL before checking pgvector" do
    incompatible = CompatibilityProbe.new(server_version_num: "170011", vector_version: EXPECTED_VECTOR_VERSION)

    error = assert_raises(Nudge::DatabaseCompatibility::IncompatibleDatabaseError) do
      Nudge::DatabaseCompatibility.verify!(incompatible)
    end

    assert_equal "PostgreSQL 18 is required; server_version_num=170011", error.message
    assert_equal [ "SHOW server_version_num" ], incompatible.queries
  end

  test "rejects a missing or incompatible pgvector extension" do
    [ nil, "0.8.4" ].each do |version|
      incompatible = CompatibilityProbe.new(server_version_num: "180004", vector_version: version)

      error = assert_raises(Nudge::DatabaseCompatibility::IncompatibleDatabaseError) do
        Nudge::DatabaseCompatibility.verify!(incompatible)
      end

      assert_equal "pgvector 0.8.5 is required; found #{version || "not installed"}", error.message
      assert_equal 2, incompatible.queries.size
    end
  end

  test "ships PostgreSQL 18 schema dump and load clients" do
    %w[pg_dump psql].each do |command|
      stdout, stderr, status = Open3.capture3(command, "--version")

      assert_predicate status, :success?, "#{command} failed: #{stderr}"
      assert_match(/PostgreSQL\) 18\./, stdout)
    end
  end

  test "stages libpq without a build architecture path" do
    dockerfile = Rails.root.join("Dockerfile").read

    refute_match(%r{/usr/lib/(?:x86_64|aarch64)-linux-gnu/libpq}, dockerfile)
    assert_includes dockerfile, "find /usr/lib -name 'libpq.so.5.18'"
    assert_includes dockerfile, "COPY --from=postgres_tools /tmp/libpq.so.5 /usr/local/lib/libpq.so.5"
  end

  test "pins pgvector when Rails regenerates the SQL structure" do
    Tempfile.create("structure.sql") do |file|
      file.write("CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;\n\n")
      file.flush

      assert Nudge::DatabaseCompatibility.pin_pgvector_structure!(file.path)
      assert_equal "#{Nudge::DatabaseCompatibility::PGVECTOR_STRUCTURE_STATEMENT}\n", File.read(file.path)
      assert Nudge::DatabaseCompatibility.pin_pgvector_structure!(file.path)
    end

    Tempfile.create("structure.sql") do |file|
      error = assert_raises(RuntimeError) do
        Nudge::DatabaseCompatibility.pin_pgvector_structure!(file.path)
      end
      assert_equal "Canonical SQL structure is missing the vector extension", error.message
    end
  end

  test "shared execution mode helper rejects mode changes only" do
    connection.execute(<<~SQL)
      CREATE TEMPORARY TABLE db01_execution_mode_probe (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        execution_mode text NOT NULL,
        note text
      ) ON COMMIT DROP
    SQL
    connection.execute(<<~SQL)
      CREATE TRIGGER db01_execution_mode_probe_immutable
      BEFORE UPDATE OF execution_mode ON db01_execution_mode_probe
      FOR EACH ROW EXECUTE FUNCTION nudge_prevent_execution_mode_change()
    SQL
    connection.execute("INSERT INTO db01_execution_mode_probe (execution_mode, note) VALUES ('fixture', 'before')")

    connection.execute("UPDATE db01_execution_mode_probe SET note = 'after'")
    assert_equal "after", connection.select_value("SELECT note FROM db01_execution_mode_probe")

    error = assert_raises(ActiveRecord::StatementInvalid) do
      connection.transaction(requires_new: true) do
        connection.execute("UPDATE db01_execution_mode_probe SET execution_mode = 'live'")
      end
    end
    assert_match(/execution_mode is immutable/, error.message)
    assert_equal "fixture", connection.select_value("SELECT execution_mode FROM db01_execution_mode_probe")
  end

  test "shared immutable row helper rejects updates and deletes" do
    connection.execute(<<~SQL)
      CREATE TEMPORARY TABLE db01_immutable_probe (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        value text NOT NULL
      ) ON COMMIT DROP
    SQL
    connection.execute(<<~SQL)
      CREATE TRIGGER db01_immutable_probe_guard
      BEFORE UPDATE OR DELETE ON db01_immutable_probe
      FOR EACH ROW EXECUTE FUNCTION nudge_prevent_row_mutation()
    SQL
    connection.execute("INSERT INTO db01_immutable_probe (value) VALUES ('original')")

    update_error = assert_raises(ActiveRecord::StatementInvalid) do
      connection.transaction(requires_new: true) do
        connection.execute("UPDATE db01_immutable_probe SET value = 'changed'")
      end
    end
    assert_match(/rows are immutable/, update_error.message)

    delete_error = assert_raises(ActiveRecord::StatementInvalid) do
      connection.transaction(requires_new: true) do
        connection.execute("DELETE FROM db01_immutable_probe")
      end
    end
    assert_match(/rows are immutable/, delete_error.message)
    assert_equal "original", connection.select_value("SELECT value FROM db01_immutable_probe")
  end

  private

  CompatibilityProbe = Data.define(:server_version_num, :vector_version, :queries) do
    def initialize(server_version_num:, vector_version:)
      super(server_version_num:, vector_version:, queries: [])
    end

    def select_value(query)
      queries << query
      query == "SHOW server_version_num" ? server_version_num : vector_version
    end
  end

  def connection
    ActiveRecord::Base.connection
  end
end
